### ISSUE TITLE
Too much image noise using Kevin Beason's smallpt

### ISSUE THREAD

**Issue by hbhutta** [matt77hias/cpp-smallpt#1]
I just ran Kevin Beason's code for [smallpt](http://www.kevinbeason.com/smallpt/smallpt.txt) and I have a lot of noise in my image. I am completely new to ray tracing and I ran the code in order to understand what it does, I did not expect the image noise. I also did not make any changes to Kevin's code. Here is the image.ppm file that I get in comparison to his:
![image](https://user-images.githubusercontent.com/112280419/232853444-0f2c6df4-dd4a-42ea-81ea-6632d28fcda8.png). How do I remove this noise?

**Comment by hbhutta** [comment]
Hello, any suggestions to remove image noise would be helpful.

**Comment by matt77hias** [comment]
The perceived noise is due to the variance on the Monte Carlo estimators, estimating the radiance per pixel. Reducing the variance, will reduce the noise. For a more in depth study about variance reduction techniques, I refer to Eric Veach's PhD thesis: _Robust Monte Carlo Methods for Light Transport Simulation_ and any research derived thereof. But be aware, most of these techniques, will require substantial changes to the `smallpt` code base. `smallpt` as is only supports brute force increasing the number of samples per (sub)pixel, which can be passed as an argument to the executable. In the absence of such an argument, the minimum 1 sample per subpixel, 4 samples per pixel will be used.

**Comment by hbhutta** [comment]
Thank you. I am a mathematics student although I am completely new to ray tracing and graphics in general. I will look into the study you mention.

**Comment by matt77hias** [comment]
But as mentioned before, if you only care about getting a prettier picture, you can execute the program for example as ```cpp-smallpt.exe 5000``` with 5000 samples per pixel (_instead of the default of 4 samples per pixel_) similar to what was used for the image you provided.
